import { TableHeaderOption } from '@/types'

export const customerListHeadCells: TableHeaderOption[] = [
  {
    id: 'id',
    align: 'left',
    disablePadding: true,
    label: 'Customer Code',
    checked: false,
  },
  {
    id: 'customerName',
    align: 'left',
    disablePadding: true,
    label: 'Customer Name',
    checked: false,
  },
  {
    id: 'abbreviation',
    align: 'left',
    disablePadding: true,
    label: 'Customer Abbreviation',
    checked: false,
  },
  {
    id: 'market',
    align: 'left',
    disablePadding: true,
    label: 'Market',
    checked: false,
  },
  {
    id: 'languageIds',
    align: 'left',
    disablePadding: true,
    label: 'Language',
    checked: false,
  },
  {
    id: 'service',
    align: 'left',
    disablePadding: true,
    label: 'Service',
    checked: false,
  },
  {
    id: 'branch',
    align: 'left',
    disablePadding: true,
    label: 'Branch',
    checked: false,
  },
  {
    id: 'divisions',
    align: 'left',
    disablePadding: true,
    label: 'Division',
    checked: false,
  },
  {
    id: 'contactName',
    align: 'left',
    disablePadding: true,
    label: 'Contact Name',
    checked: false,
  },
  {
    id: 'collaborationStartDate',
    align: 'left',
    disablePadding: true,
    label: 'Collaboration Start date',
    orderBy: 'desc',
    useSort: true,
    sortBy: 'collaborationStartDate',
    checked: false,
  },
  {
    id: 'priority',
    align: 'left',
    disablePadding: true,
    label: 'Priority',
    checked: false,
  },
  {
    id: 'status',
    align: 'center',
    disablePadding: true,
    label: 'Status',
    checked: false,
  },
]
